spring:
  application:
    name: medicore-backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://127.0.0.1:5433/medicore}
    username: ${DATABASE_USERNAME:medicore}
    password: ${DATABASE_PASSWORD:medicore}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: ${PORT:4110}
  address: 0.0.0.0

medicore:
  jwt:
    secret: ${JWT_SECRET:medicore-dev-jwt-secret-change-in-production}
    expiration-ms: 604800000
  cors-origins: ${CORS_ORIGIN:http://127.0.0.1:3000,http://localhost:3000}
  app-url: ${APP_URL:http://127.0.0.1:3000}
  push:
    vapid-public-key: ${VAPID_PUBLIC_KEY:BOG1zGSwGchL4mT1ThqrAfs3o12rUaIC-pkogOec6z9eco8f-EcqS5yCIwiRPnSOHbi2oihv-QGHz3NF9VVitf0}
    vapid-private-key: ${VAPID_PRIVATE_KEY:8rgByt73ue30jBdXYLSUlUiBsFI2NP0b5eUnZC4r_Zk}
    vapid-subject: ${VAPID_SUBJECT:mailto:care@medicore.local}

logging:
  level:
    org.springframework.security: INFO
